
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ypukyiwwvhvznxxasbhb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdWt5aXd3dmh2em54eGFzYmhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzNDg5MDQsImV4cCI6MjA1NjkyNDkwNH0.5YGMdzrxaUCorxzG5hC7398rTYiYfHxUm3vQGafGfqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
